### PR TITLE
spaces between constants, properties and first method

### PR DESCRIPTION
**Pull request by TomasVotruba**
Previous talk: https://github.com/Symplify/Symplify/pull/338#discussion_r136986985 

@dg Your feelings were right - **spaces between methods are checked** by:
https://github.com/nette/coding-standard/blob/master/src/Sniffs/WhiteSpace/FunctionSpacingSniff.php

Spaces between constants and properties are missed though:

image

See [Travis fail report lines](https://travis-ci.org/nette/coding-standard/jobs/272108523#L568-L575).

image

Shall we add that?

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I guess it would be more complicated, because at the moment it's very variable:

- 1 space between properties
- 0 space between constants (some with `const` before each, some grouped with single `const`)
- 1 space between constants with annotation
- 2 spaces between last constants/property and method

It would make sense to have just 1 rule for these elements: e.g. 1 space.

**Comment by dg** [comment]
I'm trying to use it 2 spaces before methods and 1 space before property or class declaration.

2 spaces between methods is favorite default and it should not be changed to 1.

**Comment by TomasVotruba** [comment]
Sorry, I didn't make myself clear. I talked **about properties and constants only**, not about methods.
Anything else would require lot of work now.

So from your comment this would go:

>  1 space before property

**Comment by dg** [comment]
Oh yes, 1 space between constants and properites declaration is fine :)

**Comment by TomasVotruba** [comment]
False positives

image

image

---

**Comment by TomasVotruba** [comment]
What about this one? I think it would make sense to keep it the same for both properties and constants - 1 space. 

image

I'd have to create ConstantSpacingFixer otherwise and it's not consistent with:

image

**Comment by dg** [comment]
I trying it on nette/application and it tells me that it found some bugs (cca 16× ClassAndTraitVisibilityRequiredFixer + 22× PropertyAndConstantSeparationFixer), fixed them, but no files was changed.

**Comment by dg** [comment]
Sure, keeping one line between constants makes sense.

Well, except for this:

```
const
    A = 1,
    B =2;
```

**Comment by TomasVotruba** [comment]
Kk, that seems reasonable

**Comment by TomasVotruba** [comment]
I've just added `Symplify\CodingStandard` that allows comments behind constants - that resolve issue I mentioned above.

**Comment by TomasVotruba** [comment]
I retried with temp package:

```bash
composer create-project nette/application temp/nette-application
```

and simple setup:

```
# easy-coding-standard.neon
checkers:
    - Nette\CodingStandard\Fixer\ClassNotation\ClassAndTraitVisibilityRequiredFixer

    # Constants and Properties should be separated by 1 empty line
    Symplify\CodingStandard\Fixer\ClassNotation\PropertyAndConstantSeparationFixer:
        space_count: 1

    # Last property and 1st method should be separated by 2 empty line
    Symplify\CodingStandard\Fixer\ClassNotation\LastPropertyAndFirstMethodSeparationFixer:
        space_count: 2
```


```bash
./ecs check temp/nette-application --clear-cache
```

Found around 200 errors. So I tried to fix them:

```bash
./ecs check temp/nette-application --clear-cache --fix
```

And it fixed ~30 files.

**Comment by TomasVotruba** [comment]
Ping @dg , this is ready. Could you try it?

**Comment by dg** [comment]
Tomorrow I will try it!

**Comment by dg** [comment]
It still writes that it has fixed a lot of bugs, but it does not change any files.

The reason is that one fixer adds a space, another removes it again, so it looks like two fixes, but nothing has changed.

**Comment by dg** [comment]
It seems to me that `PropertyAndConstantSeparationFixer` turns this code:

```php
class XXX
{
	public $var;


	public function __construct()
```

into this


```php
class XXX
{
	public $var;

	public function __construct()
```

The `LastPropertyAndFirstMethodSeparationFixer` has no effect.

And `Nette\CodingStandard\Sniffs\WhiteSpace\FunctionSpacingSniff` turns it back again.

**Comment by TomasVotruba** [comment]
> It seems to me that PropertyAndConstantSeparationFixer turns this code:

Mmm, that shouldn't happen. I will look on it.

**Comment by TomasVotruba** [comment]
I tried this configuration:

```yaml
checkers:
    - Symplify\CodingStandard\Fixer\ClassNotation\PropertyAndConstantSeparationFixer
    Symplify\CodingStandard\Fixer\ClassNotation\LastPropertyAndFirstMethodSeparationFixer:
        space_count: 2
```

On this file:

```php
<?php declare(strict_types=1);

class XXX
{
    public $var;


    public function __construct()
    {
    }
}
```

With 0 errors:

image


Coudl you replicate and/or modify the configuration to cause some error?

**Comment by TomasVotruba** [comment]
(Rebased on master)

**Comment by TomasVotruba** [comment]
I've added the setup to config `pull-request-16.neon` (can be remove after this is solved) and to the Travis (see `composer.json`).

If this pass, it's probably related to Windows in some way.

**Comment by TomasVotruba** [comment]
If it still doesn't work, just let me know and I'll stop by :wine_glass:

**Comment by dg** [comment]
Hmmm, on your example it works correctly…

**Comment by dg** [comment]
On this example:

```php
<?php

/**
 * This file is part of the Nette Framework (https://nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 */

declare(strict_types=1);

namespace Nette\Application;

use Nette\Http;


/**
 * The exception that indicates client error with HTTP code 4xx.
 */
class BadRequestException extends \Exception
{
	/** @var int */
	protected $code = Http\IResponse::S404_NOT_FOUND;


	public function __construct(string $message = '', int $httpCode = 0, \Exception $previous = null)
	{
		parent::__construct($message, $httpCode ?: $this->code, $previous);
	}


	public function getHttpCode(): int
	{
		return $this->code;
	}
}


/**
 * Forbidden request exception - access denied.
 */
class ForbiddenRequestException extends BadRequestException
{
	/** @var int */
	protected $code = Http\IResponse::S403_FORBIDDEN;


}
```

with `pull-request-16.neon` it always tells that `2 errors successfully fixed and no other found!` but file is unchanged.

**Comment by TomasVotruba** [comment]
Awesome, that's what I needed

**Comment by dg** [comment]
I am idiot, I posted wrong code! Now it is correct.

**Comment by TomasVotruba** [comment]
No, you're not. I've just update the code to include only code needed to reproduce the issue:

```php
<?php

class SomeClass
{
    private $someProperty;


}


class AnotherClass
{
    private $someOtherProperty;
}
```

I got all I need now. Just a minute...

**Comment by TomasVotruba** [comment]
**Fixed** in Symplify\CodingStandard: https://github.com/Symplify/Symplify/pull/370/files#diff-de0cc99fae9c57ebde2a81f37d2a71ca

**Released** in Symplify\CodingStandard 2.4.2: https://github.com/Symplify/Symplify/releases/tag/v2.4.2

**Comment by TomasVotruba** [comment]
I've added your test case and it passes: https://github.com/nette/coding-standard/pull/16/commits/8f534b725e1b268822845af07c471435eb9155b3

Can I merge this (after removing test temp data)?

**Comment by dg** [comment]
I tested it over the whole Nette and it works great, thanks!

**Comment by TomasVotruba** [comment]
Awesome :)

**Pull request merged**
