### PR TITLE
updated ECS to 5.1.1

### PR DESCRIPTION
**Pull request by foxycode**
Tested on few Nette apps, everything seems ok.

### CODE REVIEW

**Comment by dg** [comment]
Great!

**Comment by dg** [comment]
It generates error

```
In Container.php line 277:

  You have requested a non-existent service "Symfony\Component\Console\Input\InputInterface".
```

Do you know how to fix it?

**Comment by foxycode** [comment]
@dg On which repository? I tested on `nette/application` and everything seems to work ok.

**Comment by dg** [comment]
It triggers error immediately, when I run ecs.

**Comment by foxycode** [comment]
@dg On which PHP? I see no errors.

**Comment by foxycode** [comment]
@dg Can you provide more info? I tried on more apps, with more PHP versions and everything seems ok on my side.

**Comment by dg** [comment]
For example see Travis https://travis-ci.org/nette/coding-standard/jobs/482049061

**Comment by foxycode** [comment]
@TomasVotruba I can't reproduce the problem. Can you look at this please?

**Comment by foxycode** [comment]
@TomasVotruba We are locked to `5.4.0` because `5.4.1` is requiring `symplify/coding-standard` in version `^5.5` which is dev. Can you release stable?

@dg Can we use dev versions (add `minimum-stability: dev` to `composer.json`)?

**Comment by dg** [comment]
`minimum-stability: dev` leads to another error:

```
PHP Fatal error:  Interface 'Psr\SimpleCache\CacheInterface' not found in W:\Nette\x-coding-standard\vendor\symfony\cache\Simple\AbstractCache.php on line 28
```

**Comment by dg** [comment]
@TomasVotruba The problem still persists. 

```
symplify/better-phpdoc-parser  v5.4.1   Slim wrapper around phpstan/phpdoc-parser with format preserving printer
symplify/coding-standard       v5.4.1   Set of Symplify rules for PHP_CodeSniffer and PHP CS Fixer.
symplify/easy-coding-standard  v5.4.1   Use Coding Standard with 0-knowledge of PHP-CS-Fixer and PHP_CodeSniffer.
symplify/package-builder       v5.4.1   Dependency Injection, Console and Kernel toolkit for Symplify packages.
symplify/token-runner          v5.4.1   Set of utils for PHP_CodeSniffer and PHP CS Fixer
```

**Comment by TomasVotruba** [comment]
> minimum-stability: dev is not related to releasing, ie. composer create-project installs stable packages no matter how minimum-stability is set.

It is. Repository can work, since it uses these, while tagged packages don't.

**Comment by dg** [comment]
It seems that problem was in /esc file, I updated it and it works.

**Comment by foxycode** [comment]
Great :)

**Pull request merged**
