### PR TITLE
Updated to ECS 5.5 (required for Nette 3)

### PR DESCRIPTION
**Pull request by ikeblaster**
I am adding this for future reference and testing. 

[symplify/easy-coding-standard](https://github.com/Symplify/EasyCodingStandard) and [symplify/coding-standard](https://github.com/Symplify/CodingStandard) are still in a dev phase. Other than that it seems to be working well with Nette 3 and doing what it should (it finds same errors in our project as v2.1.2). Tests are passing ([see CI](https://travis-ci.org/ikeblaster/coding-standard)), but they don't seem to be really thorough.

### CODE REVIEW

**Comment by dg** [comment]
Please fix it to specific versions (ie `5.5.1` instead of `5.5`), because in the patch versions there are often changes that break the Nette Coding Standard.

**Comment by dg** [comment]
Btw file `esc` should be fixed too, I updated travis to check it correctly.

**Comment by ikeblaster** [comment]
Thank you for pointing out `ecs`. I fixed it.

---

I might have not stated it clearly - this PR is not _in shape_ for merging at this moment.

There is no release of those two symplify packages => no 5.5.1 version. I also had to add `"minimum-stability": "dev"` which is something you probably don't want in the final code.

**Comment by dg** [comment]
I understand :-)

Just saying that exactly versions are needed when you use ECS, because otherwise there are big problems with it.

**Comment by foxycode** [comment]
@db Closed by https://github.com/nette/coding-standard/pull/36

**Pull request closed without merging**
