### PR TITLE
[suggestion] Single empty line between class elements

### PR DESCRIPTION
**Pull request by TomasVotruba**
This is proposal to Nette Coding Standard v0.8.

It is related to **property, constants and method mutual spacing in class elements**

```php
class SomeClass
{
    public $property;

    public $otherProperty;

    const SOME_CONSTANT = 1;


    public function someMethod();
}
```

At the moment, we have 3 checkers and 3 rules that try to take care of it:

- `Nette\CodingStandard\Sniffs\WhiteSpace\FunctionSpacingSniff`
- `Symplify\CodingStandard\Fixer\ClassNotation\LastPropertyAndFirstMethodSeparationFixer` 
- and `Symplify\CodingStandard\Fixer\ClassNotation\PropertyAndConstantSeparationFixer` (deprecated since Symplify 3.0)

**I propose to use official `ClassAttributesSeparationFixer` and use 1 empty line for all of these elements**.

### The Reasons

- PHP CS Fixer introduced a [`ClassAttributesSeparationFixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.9/src/Fixer/ClassNotation/ClassAttributesSeparationFixer.php) (`class_attributes_separation`) fixer that handles spaces between properties, constants and methods, this, [see PR](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3098) in version 2.8 (2.9 is last one in time being) - it works like a charm thanks to @SpacePossum
- **this fixer works better than our 3 in combination**; I found this out after using it :)
- **we will get better result, since our checkers are not so good tested** (or not at all)
- we could delegate responsbility to external tool and focus our attention on improvements of this package like #19

### Demo

I've setup standalone demo build in Travis, that checks `/vendor/nette` with only this fixer, to see how it'd look like.

```diff
 class SomeClass
 {
     public $property;

     public $otherProperty;

     const SOME_CONSTANT = 1;
-

     public function someMethod();
 }
```

This would save so much time and possible edge-case solving by using already-invented wheel.

After this there is nothing to prevent 0.8 release with many fixes after almost 3,5 months.

What do you think @dg @nette/core @f3l1x @aleswita @venca-x

### CODE REVIEW

**Comment by JanTvrdik** [comment]
I think it's a bad idea.

**Comment by dg** [comment]
Can be ClassAttributesSeparationFixer hardfixed?

**Comment by TomasVotruba** [comment]
@dg It might be. But I'm not sure much work would it take to differentiate for all 3 kinds.

**Comment by f3l1x** [comment]
Well, thanks for the PR. I prefer 1 empty line before methods in my codes, but I'm also oukey with 2 empty lines in Nette. I understand your thoughts.

**Comment by TomasVotruba** [comment]
@JanTvrdik I personally use IDE to [improve readability with font size, line height, colors](https://laracasts.com/series/how-to-be-awesome-in-phpstorm/episodes/2) and display resolution. When you can focus only 2 lines tops at once, the number of spaces doesn't matter.
2+ spaces only slows-down reading then, because I need to scroll. Current syntax is inconsisten and thus less readable.

**Comment by TomasVotruba** [comment]
Closing as community is still ambiguous about this. 
Not a priority for me anymore.

**Pull request closed without merging**
