### PR TITLE
setting up few basic rules

### PR DESCRIPTION
**Pull request by TomasVotruba**
This proposal is based on:

- [General Rules](https://nette.org/en/coding-standard#toc-general-rules) in documentation
- current Nette 3.0 code, mainly PHP 7.1 related features

All rules can be changed, removed, added and modified of course.

### CODE REVIEW

**Comment by f3l1x** [comment]
@TomasVotruba Look's good. But, I'm not sure if it's good idea to make a dependency on simplify package. Why couldn't we just use pure codesniffer?

**Comment by TomasVotruba** [comment]
@f3l1x Why do you think so?

This tool combines CodeSniffer and PHP-CS-Fixer in easy to understand way. To extend, maintain and develop.

**Comment by f3l1x** [comment]
@TomasVotruba Well, I like Nette for its straightforward and simplicity. No useless dependencies and no other stuff. Everything is as closed as possible. It brings more overhead, otherwise it's really great. 

I like `symplify/easy-coding-standard`, I really do. I believe this package could be a first step to some quality assurance and could become a standard for many nette-based 3rd party libraries. 

That's my opinion and I'm cool with this solution too, you know..  

/cc @dg @fprochazka @chemix @milo @jantvrdik

**Comment by TomasVotruba** [comment]
@f3l1x This package is about coding standard, set of rules from the docs validated by PHP. Nothing more.

If I understand you correctly, you want to create a new tool, another CodeSniffer or PHP-CS-Fixer. If so, you can contribute to Code Checker: https://github.com/nette/code-checker

I'm nose I understand though.

**Comment by fprochazka** [comment]
If it's doable, I'd preffer this package to use code sniffer and cs fixer directly. But hey, I'm probably not gonna be maintaining this, so whatever works for you :)

Also, requring `@dev` of `symplify/easy-coding-standard` is fine for now, but you should probably release it before tagging this (nette/cs) repo. (Which you probably know already)

Btw https://packagist.org/packages/symplify/easy-coding-standard has no license.

**Comment by TomasVotruba** [comment]
@fprochazka Thanks for your message. I'll integrate all points you wrote, before tagging or promoting this package. 

> Also, requring @dev of symplify/easy-coding-standard is fine for now, but you should probably release it before tagging this repo. (Which you probably know already)

I might know, but I also might forget :)

> Btw https://packagist.org/packages/symplify/easy-coding-standard has no license.

I wasn't sure about license in `composer.json`, if anyone uses or reads it, so this helped me.

**Comment by fprochazka** [comment]
It's pretty hard to overlook :) 

image

**Comment by dg** [comment]
Great work, thanks!

**Comment by TomasVotruba** [comment]
@dg Thank you! I'm glad you like it.

I will find time to add some more rules today.

**Comment by TomasVotruba** [comment]
Yep. 

I will try reinstall it when I get home, that might help. Thanks for inspiration

**Comment by TomasVotruba** [comment]
@fprochazka I'm glad I'm not the only one. Started to feel weird.

@dg `end_of_line` dropped, same for `indent_size`. We can change that later if needed.

**Comment by TomasVotruba** [comment]
Merging, so this PR won't grow too huge and to make this repository open to PRs.

**Pull request merged**
